name: always
on: workflow_dispatch
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "all is well"
      - name: second_step
        run: echo "all is well"
      
    
